development:
  cloudinary: <%= ENV['CLOUDINARY_URL'] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloudinary: <%= ENV['CLOUDINARY_URL'] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloudinary: <%= ENV['CLOUDINARY_URL'] %>
  enhance_image_tag: true
  static_file_support: false